version: '3.9'
services:

  postgres:
    tty: true
    image: postgres:16.1-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: "event_users"
      POSTGRES_USER: "rakhymzhan"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - api
  auth:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/event_users
      SPRING_DATASOURCE_USERNAME: rakhymzhan
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - api

volumes:
  postgres:
    driver: local
networks:
  api:
    driver: bridge